### ISSUE TITLE
Add ref to Responses

### ISSUE THREAD

**Issue by sskserk** [davidebianchi/gswagger#126]
Hi @davidebianchi,

Is there a way to add a reference to component/definition to a response (gswagger.Definitions)?  Right now seems it only accepts pure schemas but not refs to the schemas.

Thank you!

**Comment by davidebianchi** [comment]
Hi @sskserk

I'm sorry for the late reply. Yes, at the moment we only support pure schemas and not refs. It's a feature we could add in the future. It is blocking for you?

**Comment by sskserk** [comment]
@davidebianchi 

I wouldn't say it is blocking me. Finally, I could achieve it with the manual adding of required schemas into components and manual generation of MediaType available in the "github.com/getkin/kin-openapi". See the code fragment below:

```
mt := openapi3.NewMediaType()
mt.Schema = &openapi3.SchemaRef{Ref: "#/components/schemas/" + componentSchemaName, Value: PointerToComponentFrom_ComponentSchemas}

```
It was an interesting journey! ;-) I'm just wondering if it can be achieved anyhow automatically. Without intermediate referencing the Components. 

P/S:
Please let me know if anything is unclear. I can create a code fragment for you to make it more clear.
